version: "3"
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./data/mysql-content:/var/lib/mysql
    networks:
      - data

  ghost:
    container_name: ghost
    depends_on:
      - db
    image: ghost:alpine
    restart: always
    ports:
      - 2368:2368
    networks:
      - data
      - web
    environment: 
      url: "https://blog.lszh.io"
      database__client: "mysql"
      database__connection__host: db
      database__connection__port: 3306
      database__connection__user: root
      database__connection__database: ghost
    volumes:
      - ./data/ghost-content:/var/lib/ghost/content
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - ./nginx/blog.conf:/etc/nginx/conf.d/blog.conf
      - ./ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - ghost
    networks:
      - web

networks:
  data:
  web:
