version: "3"
services:
  db:
    container_name: db
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ghost
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - $PWD/blog-data:/var/lib/mysql
    networks:
      - data

  ghost:
    container_name: ghost
    depends_on:
      - db
    build: ./ghost
    restart: always
    ports:
      - 2368:2368
    expose:
      - 2368
    networks:
      - data
      - web
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - $PWD/nginx/blog.conf:/etc/nginx/sites-enabled/blog.conf
      - $PWD/ssl:/etc/ssl
    ports:
      - "80:80"
      - "443:443"
    expose:
      - 80
      - 443
    restart: always
    depends_on:
      - ghost
    networks:
      - web

networks:
  data:
  web:
